version: "3.9"

services:

  backend:
    build: ./backend
    container_name: resume-backend
    ports:
      - "5002:5000"

  frontend:
    build: ./frontend
    container_name: resume-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
